// Generated by https://quicktype.io

export interface Product {
    name:     string;
    title:    string;
    subtitle: string;
    home:     string;
    image:    string;
    links:    Link[];
}

export interface Link {
    title:        string;
    link:         string;
    image:        string;
    price:        number;
    subtitle:     string;
    description?: string;
}
